name: CICD Deploy Azure 
on:
 push:
   branches:
     - main
jobs:
  build:
   runs-on: ubuntu-latest 
   steps:
     - name: checkout action
       uses: actions/checkout@v2 
     - name: login to azure 
       uses: Azure/login@v2
       with:
         creds: ${{ secrets.AZURE_CREDENTIALS}}
         aks-cluster: my-aks-cluster
     - name: set up eks cluster
       uses: azure/aks-set-context@v1
         
     - name: deploy to azure 
       run: |
        kubectl apply -f ./release/kubernetes-manifests.yaml
        kubectl get pod 
        kubectl get svc 

  #
