name: CICD Deploy Azure 
on:
 push:
   branches:
     - main
jobs:
  build:
   runs-on: ubuntu-latest 
   steps:
     - name: checkout action
       uses: actions/checkout@v2 
     - name: login to azure 
       uses: azure/login@v2
       with:
         cred: ${{ secrets.AZURE_CREDENTIALS}}
         aks-cluster: my-aks-cluster
         enable-AzPSSession: false
         environment: azurecloud
         allow-no-subscriptions: false
         audience: api://AzureADTokenExchange
         auth-type: SERVICE_PRINCIPAL
     - name: deploy to azure 
       run: |
        kubectl apply -f ./release/kubernetes-manifests.yaml
        kubectl get pod 
        kubectl get svc 
